name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  release:
    types: ["published"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: "temurin"

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.6

    #- name: Build with Maven
      # run: mvn clean install

    - name: Get Latest Tag
      id: latesttag
      uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
            
    - name: Set REPO_ENV variable
      run: |
        REPO_NAME_LOWER=$(echo "${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" | tr '[:upper:]' '[:lower:]')
        echo "REPO_NAME=${REPO_NAME_LOWER}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t ${{ env.REPO_NAME }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: docker image tag ${{ env.REPO_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.latesttag.outputs.tag }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.latesttag.outputs.tag }}

  update-deployment:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the Deployment_ToDo_App repository
      uses: actions/checkout@v2
      with:
        repository: PaymentMicroserviceApp/Deployment_ToDo_App
        path: deployment_repo
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Update values.yml with new tag
      run: |
        cd deployment_repo/users-api
        sed -i 's/tag: .*/tag: '${{ steps.latesttag.outputs.tag }}'/' values.yml
        git config --global user.email "{{ secrets.DOCKER_USERNAME }}"
        git config --global user.name "Daniela Bonilla Caceres"
        git add values.yml
        git commit -m "Update image tag to ${{ steps.latesttag.outputs.tag }}"
        git push
